Repository thinkswell/javascript-mini-projects, pull requests merged in 2023-10, with the labels that each got.

#694 generate random number
  GenerateRandomNumber/tedante/README.md
  GenerateRandomNumber/tedante/assets/generate-random-number.png
  GenerateRandomNumber/tedante/index.html
Labels: changeRequested

#705 Made Novelty Calculator in pure HTML, CSS, Vanilla JavaScript
  NoveltyCalculator/Yasir761/README.md
  NoveltyCalculator/Yasir761/Screenshot .png
  NoveltyCalculator/Yasir761/Script.js
  NoveltyCalculator/Yasir761/Style.css
  NoveltyCalculator/Yasir761/index.html
Labels: changeRequested

#640 [ADDED]: Nokia3310_SnakeGame
  SnakeGame/Killer2OP/README.md
  SnakeGame/Killer2OP/app.js
  SnakeGame/Killer2OP/index.html
  SnakeGame/Killer2OP/style.css
Labels: changeRequested

#724 Enhanced Calculator
  Calculator/sushil-2803/style.css
Labels: invalid

#734 Guessing the random number project
  NumberGuessingGame/vinay-s36/README.md
  NumberGuessingGame/vinay-s36/index.html
  NumberGuessingGame/vinay-s36/script.js
  NumberGuessingGame/vinay-s36/style.css
Labels: changeRequested

#711 Added a Random Joke Display App with Dark Mode Toggle.
  JokeGenerator/sonicdashh/README.md
  JokeGenerator/sonicdashh/image-1.png
  JokeGenerator/sonicdashh/image.png
  JokeGenerator/sonicdashh/random-joke-generator/index.html
  JokeGenerator/sonicdashh/random-joke-generator/script.js
  JokeGenerator/sonicdashh/random-joke-generator/style.css
Labels: changeRequested

#747 React news app
  Newsapp/Athul/.gitignore
  Newsapp/Athul/newapi.json
  Newsapp/Athul/package-lock.json
  Newsapp/Athul/package.json
  Newsapp/Athul/public/README.md
  Newsapp/Athul/public/favicon.ico
  Newsapp/Athul/public/index.html
  Newsapp/Athul/public/logo192.png
  Newsapp/Athul/public/logo512.png
  Newsapp/Athul/public/manifest.json
  Newsapp/Athul/public/robots.txt
  Newsapp/Athul/src/App.css
  Newsapp/Athul/src/App.js
  Newsapp/Athul/src/App.test.js
  Newsapp/Athul/src/componets/NavBar.js
  Newsapp/Athul/src/componets/News.js
  Newsapp/Athul/src/componets/NewsItem.js
  Newsapp/Athul/src/componets/Spinner.js
  Newsapp/Athul/src/componets/gear.gif
  Newsapp/Athul/src/index.css
  Newsapp/Athul/src/index.js
  Newsapp/Athul/src/logo.svg
  Newsapp/Athul/src/reportWebVitals.js
  Newsapp/Athul/src/setupTests.js
Labels: changeRequested

#770 PingPong
  PingPongGame/AckermanLevi1/index.html
  PingPongGame/AckermanLevi1/index.js
Labels: spam

#754 Sorting Visualizer
  SortingVisualizer/Abhineshjha/README.md
  SortingVisualizer/Abhineshjha/index.html
  SortingVisualizer/Abhineshjha/script.js
  SortingVisualizer/Abhineshjha/style.css
Labels: changeRequested

#762 Sorting Visualizer
  SortingVisualizer/ayan-joshi/Readme.md
  SortingVisualizer/ayan-joshi/index.html
  SortingVisualizer/ayan-joshi/script.js
  SortingVisualizer/ayan-joshi/style.css
Labels: changeRequested

#742 Created Tetris game using js
  TetrisGame/luv2027/Tetris Game.gif
  TetrisGame/luv2027/css/js/app.js
  TetrisGame/luv2027/css/style.css
  TetrisGame/luv2027/images/blue_block.png
  TetrisGame/luv2027/images/green_block.png
  TetrisGame/luv2027/images/navy_block.png
  TetrisGame/luv2027/images/peach_block.png
  TetrisGame/luv2027/images/pink_block.png
  TetrisGame/luv2027/images/purple_block.png
  TetrisGame/luv2027/images/yellow_block.png
  TetrisGame/luv2027/index.html
Labels: changeRequested

#876 Real-time Currency Conversion with Styling Enhancements
  CurrencyConverter/malivinayak/index.html
  CurrencyConverter/malivinayak/script.js
  CurrencyConverter/malivinayak/styles.css
Labels: changeRequested

#874 Added Speech to text reader
  VoiceGenerator/shanvijha/README.md
  VoiceGenerator/shanvijha/img/angry.jpg
  VoiceGenerator/shanvijha/img/drink.jpg
  VoiceGenerator/shanvijha/img/food.jpg
  VoiceGenerator/shanvijha/img/grandma.jpg
  VoiceGenerator/shanvijha/img/happy.jpg
  VoiceGenerator/shanvijha/img/home.jpg
  VoiceGenerator/shanvijha/img/hurt.jpg
  VoiceGenerator/shanvijha/img/outside.jpg
  VoiceGenerator/shanvijha/img/sad.jpg
  VoiceGenerator/shanvijha/img/scared.jpg
  VoiceGenerator/shanvijha/img/school.jpg
  VoiceGenerator/shanvijha/img/tired.jpg
  VoiceGenerator/shanvijha/img/uncompressed/angry.jpg
  VoiceGenerator/shanvijha/img/uncompressed/drink.jpg
  VoiceGenerator/shanvijha/img/uncompressed/food.jpg
  VoiceGenerator/shanvijha/img/uncompressed/grandma.jpg
  VoiceGenerator/shanvijha/img/uncompressed/happy.jpg
  VoiceGenerator/shanvijha/img/uncompressed/home.jpg
  VoiceGenerator/shanvijha/img/uncompressed/hurt.jpg
  VoiceGenerator/shanvijha/img/uncompressed/outside.jpg
  VoiceGenerator/shanvijha/img/uncompressed/sad.jpg
  VoiceGenerator/shanvijha/img/uncompressed/scared.jpg
  VoiceGenerator/shanvijha/img/uncompressed/school.jpg
  VoiceGenerator/shanvijha/img/uncompressed/tired.jpg
  VoiceGenerator/shanvijha/index.html
  VoiceGenerator/shanvijha/script.js
  VoiceGenerator/shanvijha/style.css
Labels: changeRequested

#864 Added EncrypterDecrypterApp
  EncrypterDecrypterApp/M3hank/index.html
  EncrypterDecrypterApp/M3hank/scripts.js
  EncrypterDecrypterApp/M3hank/styles.css
Labels: changeRequested

#710 BackgroundGenerator/Shivam250702
  BackgroundGenerator/Shivam250702/README.md
  BackgroundGenerator/Shivam250702/image-1.png
  BackgroundGenerator/Shivam250702/image-2.png
  BackgroundGenerator/Shivam250702/image.png
  BackgroundGenerator/Shivam250702/index.html
  BackgroundGenerator/Shivam250702/script.js
  BackgroundGenerator/Shivam250702/style.css
Labels: changeRequested

#840 added simple drawing game
  DrawingGame/gurjott/index.html
  DrawingGame/gurjott/script.js
  DrawingGame/gurjott/styles.css
Labels: changeRequested

#867 Added badge and code snippet to the Readme
  README.md
Labels: documentation, enhancement

#884 Weather APP
  WeatherApp/Shuklaaa/README.md
  WeatherApp/Shuklaaa/index.html
  WeatherApp/Shuklaaa/script.js
  WeatherApp/Shuklaaa/style.css
Labels: changeRequested

#903 An Image Editing Webapp
  ImageEditor/AshishGupta18/README.md
  ImageEditor/AshishGupta18/Screenshot 2023-10-13 at 1.51.08 PM.png
  ImageEditor/AshishGupta18/app.js
  ImageEditor/AshishGupta18/index.html
  ImageEditor/AshishGupta18/logo1.png
  ImageEditor/AshishGupta18/logo3.jpeg
  ImageEditor/AshishGupta18/style.css
Labels: changeRequested

#898 Added an interactive weather app using weather app API
  WeatherApp/heeba-khan/app.js
  WeatherApp/heeba-khan/images/images/clear.png
  WeatherApp/heeba-khan/images/images/clouds.png
  WeatherApp/heeba-khan/images/images/drizzle.png
  WeatherApp/heeba-khan/images/images/humidity.png
  WeatherApp/heeba-khan/images/images/mist.png
  WeatherApp/heeba-khan/images/images/rain.png
  WeatherApp/heeba-khan/images/images/search.png
  WeatherApp/heeba-khan/images/images/snow.png
  WeatherApp/heeba-khan/images/images/wind.png
  WeatherApp/heeba-khan/index.html
  WeatherApp/heeba-khan/style.css
Labels: changeRequested

#915 Added Linear-Gradient as a micro Project
  BackgroundGenerator/05hiteshbansal/copy.png
  BackgroundGenerator/05hiteshbansal/home.css
  BackgroundGenerator/05hiteshbansal/home.html
  BackgroundGenerator/05hiteshbansal/home.js
  BackgroundGenerator/05hiteshbansal/readme.md
Labels: changeRequested

#900 Added the Random-Color-Generator
  RandomColorGenerator/Arcturus22/Image1.png
  RandomColorGenerator/Arcturus22/Image2.png
  RandomColorGenerator/Arcturus22/index.html
  RandomColorGenerator/Arcturus22/index.js
  RandomColorGenerator/Arcturus22/readme.md
  RandomColorGenerator/Arcturus22/style.css
Labels: changeRequested

#905 Random Password generater
  PasswordGenerator/assets/favicon.png
  PasswordGenerator/font/sans.ttf
  PasswordGenerator/index.html
  PasswordGenerator/main.js
  PasswordGenerator/style.css
Labels: changeRequested

#923 A simple and interactive javascript Drumkit
  Drum/amrit2611/Dockerfile
  Drum/amrit2611/README.md
  Drum/amrit2611/drumkit.css
  Drum/amrit2611/drumkit.js
  Drum/amrit2611/drums stock photo.jpg
  Drum/amrit2611/index.html
  Drum/amrit2611/sounds/boom.wav
  Drum/amrit2611/sounds/clap.wav
  Drum/amrit2611/sounds/hihat.wav
  Drum/amrit2611/sounds/kick.wav
  Drum/amrit2611/sounds/openhat.wav
  Drum/amrit2611/sounds/ride.wav
  Drum/amrit2611/sounds/snare.wav
  Drum/amrit2611/sounds/tink.wav
  Drum/amrit2611/sounds/tom.wav
  Drum/amrit2611/ss_working-project.png
  LICENSE
Labels: changeRequested

#713 Wheather App for issue #609
  WeatherApp/djv03/.gitignore
  WeatherApp/djv03/README.md
  WeatherApp/djv03/image.png
  WeatherApp/djv03/index.html
  WeatherApp/djv03/script.js
  WeatherApp/djv03/style.css
Labels: changeRequested

#665 stonePaperScissor
  RockPaperScissorsGame/arjungupta01/StonePaperScissors game/README.md
  RockPaperScissorsGame/arjungupta01/StonePaperScissors game/StonePaperScissor.js
Labels: changeRequested

#953 Unit converter project
  UnitConverter/vinay-s36/READme.md
  UnitConverter/vinay-s36/icon.png
  UnitConverter/vinay-s36/index.html
  UnitConverter/vinay-s36/script.js
  UnitConverter/vinay-s36/style.css
Labels: changeRequested

#951 Created PixSort Studio
  PixSort/HVbajoria/Screenshots/1.png
  PixSort/HVbajoria/Screenshots/2.png
  PixSort/HVbajoria/Screenshots/208.png
  PixSort/HVbajoria/Screenshots/readme.md
  PixSort/HVbajoria/index.html
  PixSort/HVbajoria/script.js
  PixSort/HVbajoria/style.scss
Labels: changeRequested

#736 Add EncryptionDecryptProgram
  EncryptionDecryptProgram/albimdkr/README.md
  EncryptionDecryptProgram/albimdkr/screenshot/1-Default-tampilan.png
  EncryptionDecryptProgram/albimdkr/screenshot/2-Proses-berhasil.png
  EncryptionDecryptProgram/albimdkr/screenshot/3-Jika-proses-gagal-karna-field-kosong.png
  EncryptionDecryptProgram/albimdkr/source-code/script.js
  EncryptionDecryptProgram/albimdkr/source-code/style.css
  EncryptionDecryptProgram/albimdkr/source-code/synchronous.html
Labels: changeRequested

#842 feat: added pokevanilla js project
  PokeVanilla/images/ascending.png
  PokeVanilla/images/delete.png
  PokeVanilla/images/descending.png
  PokeVanilla/images/hover-trash.png
  PokeVanilla/images/pikachu.png
  PokeVanilla/images/pokeball2.png
  PokeVanilla/images/trash.png
  PokeVanilla/index.html
  PokeVanilla/script.js
  PokeVanilla/style.css
Labels: changeRequested

#921 Expense Tracker
  ExpenseTracker/tusharpamnani/index.html
  ExpenseTracker/tusharpamnani/script.js
  ExpenseTracker/tusharpamnani/style.css
Labels: changeRequested
